kind: kubernetes
app: goodfork
type: web
team: training
docker_image: goodfork-app
replicas: 2
container_port: 3000
healthcheck:
  path: /health
  port: 3000
database:
  type: postgres
  db_params:
    log_statement: "none"
dns:
  zone: cglcloud
  name: goodfork
