---
kind: kubernetes
app: goodfork
team: training
version: 0.0.1
internal: true
package:
  build_dir: .
  index_document: public/index.html
  error_document: public/404.html
dns:
  zone: cglcloud
  name: goodfork
