---
kind: kubernetes
app: goodfork
team: training
version: 0.0.1
internal: true
package:
  build_dir: .
  index_document: public/index.html
  error_document: public/404.html
database:
  type: postgres
  db_params:
    log_statement: "none"
dns:
  zone: cglcloud
  name: goodfork
