
kind: kubernetes
app: goodfork
type: web
team: training
docker_image: goodfork-app
internal: true
replicas: 2
container_port: 3000
healthcheck:
  path: /api/health
  port: 3000
revisionHistoryLimit: 10
dns:
  zone: cglcloud
  name: goodfork
database:
  type: postgres
  db_params:
    log_statement: "none"
depends_on:
  dev:
    fqdn:
      - address: "api.openai.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "fonts.googleapis.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "fonts.gstatic.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "lottie.host"
        protocol: "tcp"
        ports:
          - "443"
      - address: "www.bbcgoodfood.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "images.immediate.co.uk"
        protocol: "tcp"
        ports:
          - "443"
      - address: "images.unsplash.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "cdn.pixabay.com"
        protocol: "tcp"
        ports:
          - "443"
  stage:
    fqdn:
      - address: "api.openai.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "fonts.googleapis.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "fonts.gstatic.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "lottie.host"
        protocol: "tcp"
        ports:
          - "443"
      - address: "www.bbcgoodfood.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "images.immediate.co.uk"
        protocol: "tcp"
        ports:
          - "443"
      - address: "images.unsplash.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "cdn.pixabay.com"
        protocol: "tcp"
        ports:
          - "443"
  prod:
    fqdn:
      - address: "api.openai.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "fonts.googleapis.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "fonts.gstatic.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "lottie.host"
        protocol: "tcp"
        ports:
          - "443"
      - address: "www.bbcgoodfood.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "images.immediate.co.uk"
        protocol: "tcp"
        ports:
          - "443"
      - address: "images.unsplash.com"
        protocol: "tcp"
        ports:
          - "443"
      - address: "cdn.pixabay.com"
        protocol: "tcp"
        ports:
          - "443"
