
version: "1"
secrets:
  - name: VELA_DATABASE_URL
    key: VishalGrover/goodfork/VELA_DATABASE_URL
    engine: native
    type: repo
steps:
  # docker build step
  - name: docker build
    image: docker-utilities.binrepo.cglcloud.in/enablementtools/docker-plugin:3-stable
    ruleset:
      if:
        branch: [ test-deployment ]
        event: [ push ]
    parameters:
      repo: "goodfork-app"
      skip_existing: true
      tags: "${VELA_BUILD_COMMIT:0:7}"

  # build goodfork app
  - name: build-goodfork-app
    image: node:20-alpine
    environment:
      DO_BUILD_GOODFORK_APP: 'true'
    ruleset:
      branch: [ test-deployment ]
      event: [ push, pull_request, schedule, deployment ]
    commands:
      - npm install
      - npm run build

  # deploy captain dev goodfork app
  - name: captain-deploy-goodfork-dev
    ruleset:
      branch: [ test-deployment ]
      event: [ push ]
    image: docker-utilities.binrepo.cglcloud.in/captain:1-stable
    parameters:
      env: dev
      run_apply: true
      edge_auth: false
      version: "${VELA_BUILD_COMMIT:0:7}"
      nocache: true  
